# Generated by Django 6.0.5 on 2026-05-30 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Electronics', 'Electronices'), ('Documents', 'Documents'), ('Accessoiries', 'Accessories'), ('Bags', 'Bags'), ('Others', 'Others')], max_length=20)),
                ('description', models.TextField()),
                ('found_location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('status', models.CharField(default='Found', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronices'), ('Documents', 'Documents'), ('Accessoiries', 'Accessories'), ('Bags', 'Bags'), ('Others', 'Others')], max_length=20)),
                ('description', models.TextField()),
                ('lost_location', models.CharField(max_length=200)),
                ('lost_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('status', models.CharField(default='Lost', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
