# Generated by Django 6.0.1 on 2026-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Others', 'Others')], max_length=20),
        ),
    ]
