# Generated by Django 6.0.1 on 2026-05-30 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_item'),
        ('items', '0002_alter_founditem_category_alter_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='LostItem',
        ),
    ]
