# Generated by Django 6.0.1 on 2026-05-30 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('items', '0002_alter_founditem_category_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
