# Generated by Django 6.0.1 on 2026-05-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_item'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='item',
        ),
        migrations.AddField(
            model_name='claim',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='claim',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
